config/routes.rb
SampleApp::Application.routes.draw do

  resources :users

  resources :devices

  resources :sensors

  resources :sessions, only: [:new, :create, :destroy]
  root  'static_pages#home'

  match '/signup',    to: 'users#new',              via: 'get'
  match '/signin',    to: 'sessions#new',           via: 'get'
  match '/signout',   to: 'sessions#destroy',       via: 'delete'
  match '/help',      to: 'static_pages#help',      via: 'get'
  match '/about',     to: 'static_pages#about',     via: 'get'
  match '/contact',   to: 'static_pages#contact',   via: 'get'
  match '/dashboard', to: 'static_pages#dashboard', via: 'get'

  match '/aggregate', to: 'devices#aggregate', via: 'get'

end

app/models/device.rb
class Device < ActiveRecord::Base

  belongs_to :user
  validates :user_id, presence: true

  belongs_to :device_type
  validates :device_type_id, presence: true

  validates :uuid, presence: true, length: {maximum: 32}
  validates :name, presence: true, length: {maximum: 50}

  has_many :sensors, dependent: :destroy


  def self.aggregate

    Device.get_aggregate_sensors.each { |aggregate_sensor|

      timestamps = aggregate_sensor.get_dirty_timestamps

      unless timestamps.empty?

        Device.get_aggregated_sensors(aggregate_sensor).each { |sensor|

          timestamps.each { |timestamp|

            sum = aggregate_sensor.get_measurement(timestamp) + sensor.get_measurement(timestamp)
            aggregate_sensor.add_measurement!(timestamp, sum)
          }
        }
        aggregate_sensor.clear_dirty_timestamps!

        measurements = aggregate_sensor.get_measurements(timestamps.min, timestamps.max)
        aggregate_sensor.trigger_load_event measurements
      end
    }
  end

  def self.get_aggregated_sensors(aggregate_sensor)

    sensors = []

    Device.where(user_id: aggregate_sensor.device.user_id).where.not(id: aggregate_sensor.device.id).each { |device|

      Sensor.where(device_id: device.id, sensor_type_unit_id: aggregate_sensor.sensor_type_unit.id).each { |sensor|

        sensors.push(sensor)
      }
    }
    sensors
  end

  def self.get_aggregate_sensors

    sensors = []
    aggregate_type = DeviceType.find_by(name: 'device.type.aggregate')

    Device.where(device_type_id: aggregate_type.id).each { |device|

      Sensor.where(device_id: device.id).each { |sensor|

        sensors.push(sensor)
      }
    }
    sensors
  end
end

app/models/device_type.rb
class DeviceType < ActiveRecord::Base

  has_many :devices

  validates :name, presence: true, length: {maximum: 40}
end

app/controllers/devices_controller.rb
class DevicesController < ApplicationController
  before_action :signed_in_user, only: [:index, :edit, :update, :destroy]

  def index
    @devices = Device.where(user_id: @current_user.id).paginate(page: params[:page])
  end

  def show
    @device = Device.find(params[:id])
  end

  def edit
    @device = Device.find(params[:id])
  end

  def update
    @device = Device.find(params[:id])

    if DevicePolicy.new(@current_user, @device).update?

      if @device.update_attributes(device_params)
        flash[:success] = 'Device updated'
        redirect_to @device
      else
        render 'edit'
      end

    else
      flash[:failure] = 'Not authorized.'
      redirect_to devices_path
    end
  end

  def destroy
    @device = Device.find(params[:id])

    if DevicePolicy.new(@current_user, @device).destroy?
      @device.destroy
      flash[:success] = 'Device deleted.'
      redirect_to devices_url

    else
      flash[:failure] = 'Not authorized.'
      redirect_to devices_path
    end
  end

  def aggregate
    Device.aggregate
    redirect_to devices_url
  end

  private

  def device_params
    params.require(:device).permit(:name, :uuid, :device_type_id)
  end

  # Before filters

  def signed_in_user
    unless signed_in?
      store_location
      redirect_to signin_url, notice: 'Please sign in.'
    end
  end
end

app/views/devices/_device.html.erb
<li>
  <div style="text-align: right;">
    <%= link_to t('link.details'), device %> |
    <%= link_to t('link.edit'), edit_device_path(device) %> |
    <%= link_to t('link.delete'), device, method: :delete, data: {confirm: t('message.confirm')} %>
  </div>
  <div>
    <%= image_tag("device_type#{device.device_type_id}.png", alt: 'Device') %>
    <%= device.name %>
  </div>
  <div>
    <ul class="sensors">
      <%= render device.sensors %>
    </ul>
  </div>
</li>

app/views/devices/_form.html.erb
<%= form_for(@device) do |f| %>
    <% if @device.errors.any? %>
        <div id="error_explanation">
          <h2><%= t('message.errors') %></h2>

          <ul>
            <% @device.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :name %>
      <br>
      <%= f.text_field :name %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/devices/edit.html.erb
<% provide(:title, t('title.device.update')) %>
<h1><%= t('title.device.update') %></h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@device) do |f| %>

        <%= f.label :name %>
        <%= f.text_field :name %>

        <%= f.submit t('caption.save'), class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/devices/index.html.erb
<% provide(:title, t('title.device.all')) %>
<h1><%= t('title.device.all') %></h1>

<%= will_paginate %>

<ul class="devices">
  <%= render @devices %>
</ul>

<%= will_paginate %>

app/views/devices/show.html.erb
<% provide(:title, @device.name) %>
<div class="row">
  <aside class="span4">
    <section>
      <p>
        <%= image_tag("device_type#{@device.device_type_id}.png", alt: t('title.device.single')) %>

        <%= @device.device_type.name %>
      </p>

      <h1>
        <%= @device.name %>
      </h1>

      <p>
        <br>
        <b><%= t('helpers.label.device.uuid') %>:</b> <%= @device.uuid %>
      </p>

      <p>
        <b><%= t('helpers.label.device.created') %>:</b> <%= @device.created_at %>
      </p>

      <p>
        <b><%= t('helpers.label.device.updated') %>:</b> <%= @device.updated_at %>
      </p>
    </section>
  </aside>
</div>