config/routes.rb
SampleApp::Application.routes.draw do

  resources :users

  resources :devices

  resources :sensors

  resources :sessions, only: [:new, :create, :destroy]
  root  'static_pages#home'

  match '/signup',    to: 'users#new',              via: 'get'
  match '/signin',    to: 'sessions#new',           via: 'get'
  match '/signout',   to: 'sessions#destroy',       via: 'delete'
  match '/help',      to: 'static_pages#help',      via: 'get'
  match '/about',     to: 'static_pages#about',     via: 'get'
  match '/contact',   to: 'static_pages#contact',   via: 'get'
  match '/dashboard', to: 'static_pages#dashboard', via: 'get'

  match '/aggregate', to: 'devices#aggregate', via: 'get'

end

app/models/sensor.rb
class Sensor < ActiveRecord::Base

  belongs_to :device
  validates :device_id, presence: true

  belongs_to :sensor_type_unit
  validates :sensor_type_unit_id, presence: true

  validates :uuid, presence: true, length: {maximum: 32}
  validates :name, presence: true, length: {maximum: 50}

  validates :max_value, presence: true

  def add_measurement!(timestamp, value)

    measurement_key = redis_measurement_key(timestamp)

    redis = get_redis_node(device.user_id)
    redis.multi do
      redis.set(measurement_key, value)
      redis.sadd(redis_measurements_key, measurement_key)
      add_dirty_timestamp!(timestamp)
    end
  end

  def get_measurement(timestamp)
    measurement_key = redis_measurement_key(timestamp)

    redis = get_redis_node(device.user_id)
    value = redis.get measurement_key
    value.to_f
  end

  def remove_measurement!(timestamp)

    measurement_key = redis_measurement_key(timestamp)

    redis = get_redis_node(device.user_id)
    redis.multi do
      redis.del(measurement_key)
      redis.srem(redis_measurements_key, measurement_key)
      self.add_dirty_timestamp!(timestamp)
    end
  end

  def get_all_measurements

    measurements = {}

    redis = get_redis_node(device.user_id)
    redis.smembers(redis_measurements_key).each { |key|
      timestamp = key.split(':').last
      measurements[timestamp] = redis.get key
    }
    measurements
  end

  def get_measurements(from, to)

    measurements = {}
    redis = get_redis_node(device.user_id)

    (from..to).each { |timestamp|
      value = redis.get redis_measurement_key(timestamp)
      if value
        measurements[timestamp] = value.to_f
      end
    }
    measurements
  end

  def trigger_load_event(measurements)
    WebsocketRails[channel_key].trigger('load', measurements)
  end

  def trigger_create_event(measurement)
    WebsocketRails[channel_key].trigger('create', measurement)
  end

  def channel_key
    "sensor:#{uuid}"
  end

  def get_dirty_timestamps

    redis = get_redis_node(device.user_id)
    timestamps = redis.smembers redis_dirty_timestamps_key
    unless timestamps
      timestamps = {}
    end
    timestamps
  end

  def add_dirty_timestamp!(timestamp)
    redis = get_redis_node(device.user_id)
    redis.sadd(redis_dirty_timestamps_key, timestamp)
  end

  def clear_dirty_timestamps!
    redis = get_redis_node(device.user_id)
    redis.del redis_dirty_timestamps_key
  end

  def redis_measurements_key
    "#{channel_key}:measurements"
  end

  def redis_measurement_key(timestamp)
    "#{redis_measurements_key}:#{timestamp}"
  end

  def redis_dirty_timestamps_key
    "sensor:#{device.user_id}:#{sensor_type_unit.sensor_type_id}:dirty:timestamps"
  end
end

app/models/sensor_type.rb
class SensorType < ActiveRecord::Base

  has_many :sensors

  has_many :sensor_type_units

  validates :name, presence: true, length: {maximum: 40}
end

app/controllers/sensors_controller.rb
class SensorsController < ApplicationController
  before_action :signed_in_user, only: [:update, :destroy]

  def show
    @sensor = Sensor.find(params[:id])
  end

  def edit
    @sensor = Sensor.find(params[:id])
  end

  def update
    @sensor = Sensor.find(params[:id])

    if SensorPolicy.new(@current_user, @sensor).update?

      if @sensor.update_attributes(sensor_params)
        flash[:success] = 'Sensor updated'
        redirect_to @sensor
      else
        render 'edit'
      end

    else
      flash[:failure] = 'Not authorized.'
      redirect_to devices_path
    end
  end

  def destroy
    @sensor = Sensor.find(params[:id])

    if SensorPolicy.new(@current_user, @sensor).destroy?
      @sensor.destroy
      flash[:success] = 'Sensor deleted.'
      redirect_to devices_path

    else
      flash[:failure] = 'Not authorized.'
      redirect_to devices_path
    end
  end

  private

  def sensor_params
    params.require(:sensor).permit(:name, :uuid, :sensor_type_id, :unit_id, :min_value, :max_value)
  end

  # Before filters

  def signed_in_user
    unless signed_in?
      store_location
      redirect_to signin_url, notice: 'Please sign in.'
    end
  end
end

app/views/sensors/_form.html.erb
<%= form_for(@sensor) do |f| %>
    <% if @sensor.errors.any? %>
        <div id="error_explanation">
          <h2><%= t('message.errors') %></h2>

          <ul>
            <% @sensor.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :name %>
      <br>
      <%= f.text_field :name %>
    </div>

    <div class="field">
      <%= f.label :sensor_type %>
      <br>
      <%= f.collection_select :sensor_type_id, ::SensorType.all, :id, :name %>
    </div>

    <div class="field">
      <%= f.label :unit %>
      <br>
      <%= f.collection_select :unit_id, ::Unit.all, :id, :name %>
    </div>

    <div class="field">
      <%= f.label :min_value %>
      <br>
      <%= f.number_field :min_value %>
    </div>

    <div class="field">
      <%= f.label :max_value %>
      <br>
      <%= f.number_field :max_value %>
    </div>

    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/sensors/_sensor.html.erb
<li>
  <div class="sensor-icon-div">
    <%= image_tag("sensor_type#{sensor.sensor_type_unit.sensor_type.id}.png", alt: 'Sensor') %>
    <%= sensor.name %>
  </div>

  <div id="gauge<%= sensor.uuid %>" class="sensor-gauge-div"></div>

  <div class="sensor-links-div">
    <%= link_to t('link.details'), sensor %> |
    <%= link_to t('link.edit'), edit_sensor_path(sensor) %> |
    <%= link_to t('link.delete'), sensor, method: :delete, data: {confirm: t('message.confirm')} %>
  </div>
</li>

<%= javascript_tag defer: 'defer' do %>
    createSensorGauge("<%= sensor.uuid %>", "gauge<%= sensor.uuid %>", null, "<%= sensor.sensor_type_unit.unit.symbol %>", <%= sensor.min_value %>, <%= sensor.max_value %>);
<% end %>

app/views/sensors/edit.html.erb
<% provide(:title, t('title.sensor.update')) %>
<h1><%= t('title.sensor.update') %></h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@sensor) do |f| %>

        <%= f.label :name %>
        <%= f.text_field :name %>

        <%= f.label :sensor_type %>
        <%= f.collection_select :sensor_type_unit_id, ::SensorTypeUnit.all, :id, :name %>

        <%= f.label :min_value %>
        <%= f.number_field :min_value %>

        <%= f.label :max_value %>
        <%= f.number_field :max_value %>

        <%= f.submit t('caption.save'), class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/sensors/show.html.erb
<% provide(:title, @sensor.name) %>
<div class="row">
  <aside class="span4">
    <section>
      <p>
        <%= image_tag("device_type#{@sensor.device.device_type_id}.png", alt: t('title.device.single')) %>

        <%= @sensor.device.device_type.name %>
      </p>

      <h1>
        <%= @sensor.device.name %>
      </h1>

      <p>
        <%= image_tag("sensor_type#{@sensor.sensor_type_unit.sensor_type.id}.png", alt: t('title.sensor.single')) %>

        <%= @sensor.sensor_type_unit.sensor_type.name %>
      </p>

      <h1>
        <%= @sensor.name %>
      </h1>

      <p>
        <br>
        <b><%= t('helpers.label.sensor.uuid') %>:</b> <%= @sensor.uuid %>
      </p>

      <p>
        <b><%= t('helpers.label.sensor.created') %>:</b> <%= @sensor.created_at %>
      </p>

      <p>
        <b><%= t('helpers.label.sensor.updated') %>:</b> <%= @sensor.updated_at %>
      </p>

      <p>
        <b><%= t('helpers.label.sensor.unit') %>:</b> <%= @sensor.sensor_type_unit.unit.name %>
      </p>

      <p>
        <b><%= t('helpers.label.sensor.min_value') %>:</b> <%= @sensor.min_value %>
      </p>

      <p>
        <b><%= t('helpers.label.sensor.max_value') %>:</b> <%= @sensor.max_value %>
      </p>
    </section>
  </aside>
</div>