config/routes.rb
SampleApp::Application.routes.draw do

  resources :users

  resources :devices

  resources :sensors

  resources :sessions, only: [:new, :create, :destroy]
  root  'static_pages#home'

  match '/signup',    to: 'users#new',              via: 'get'
  match '/signin',    to: 'sessions#new',           via: 'get'
  match '/signout',   to: 'sessions#destroy',       via: 'delete'
  match '/help',      to: 'static_pages#help',      via: 'get'
  match '/about',     to: 'static_pages#about',     via: 'get'
  match '/contact',   to: 'static_pages#contact',   via: 'get'
  match '/dashboard', to: 'static_pages#dashboard', via: 'get'

  match '/aggregate', to: 'devices#aggregate', via: 'get'

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="http://www.itwm.fraunhofer.de/"><%= t('link.itwm') %></a>
  </small>
  <nav>
    <ul>
      <li><%= link_to t('title.about'), about_path %></li>
      <li><%= link_to t('title.contact'), contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <nav>
        <ul class="nav pull-right">
          <% if signed_in? %>

              <li><%= link_to t('title.dashboard'), dashboard_path %></li>

              <% if current_user.admin? %>
                  <li><%= link_to t('title.user.all'), users_path %></li>
              <% end %>

              <li><%= link_to t('title.device.all'), devices_path %></li>

              <li id="fat-menu" class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  <%= t('title.account') %> <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                  <li><%= link_to t('title.profile'), current_user %></li>
                  <li><%= link_to t('title.settings'), edit_user_path(current_user) %></li>
                  <li class="divider"></li>
                  <li>
                    <%= link_to t('link.signout'), signout_path, method: 'delete' %>
                  </li>
                </ul>
              </li>
          <% else %>
              <li><%= link_to t('link.home'), root_path %></li>
              <li><%= link_to t('title.signin'), signin_path %></li>
          <% end %>
          <li id="fat-menu" class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <%= t('link.language') %> <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><a href="<%= request.path %>?locale=en">
                <%= image_tag('en-flag.png', alt: t('label.language.english')) %>&nbsp;&nbsp;
                <%= t('label.language.english') %></a></li>

              <li><a href="<%= request.path %>?locale=de">
                <%= image_tag('de-flag.png', alt: t('label.language.deutsch')) %>&nbsp;&nbsp;
                <%= t('label.language.deutsch') %></a></li>
            </ul>
          </li>
          <li><%= link_to t('title.help'), help_path %></li>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
  <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
  <![endif]-->
</head>
<body>
<%= render 'layouts/header' %>
<div class="container">
  <% flash.each do |key, value| %>
      <%= content_tag(:div, value, class: "alert alert-#{key}") %>
  <% end %>
  <%= yield %>
  <%= render 'layouts/footer' %>
</div>
</body>
</html>